# Generated by Django 5.0.6 on 2024-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('experience', models.TextField()),
                ('reference_number', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
    ]
