# Generated by Django 5.0.6 on 2024-06-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_image_vehicletype_alter_contact_time_added_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
