# Generated by Django 5.0.6 on 2024-06-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_descriptionc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionc',
            old_name='content',
            new_name='description_text',
        ),
        migrations.RemoveField(
            model_name='descriptionc',
            name='title',
        ),
    ]
