# Generated by Django 5.0.6 on 2024-07-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
